site_name: Drift Detection Server
site_description: The documentation of Drift Detection Server
site_url: https://smolendawid.github.io/drift-detection-server/
repo_url: https://github.com/smolendawid/drift-detection-server
edit_uri:
copyright: Dawid Smoleń
plugins:
  - mkdocstrings
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light-green
      accent: amber
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Concepts:
      - Flexibility: concepts/flexibility.md
      - Parallel Training and Prediction: concepts/parallel_training_and_prediction.md
