[tool.poetry]
name = "drifting"
version = "0.0.0"
description = ""
authors = ["Dawid Smoleń"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.1"
tag_format = "v$version"
version_files = [
    "drifting/version.py",
    "pyproject.toml:version"
]
