name: Build and Deploy Docs
on:
  push:
    branches:
      - main

    paths:
      # Only rebuild website when docs have changed
      # Comment out when testing locally via act!
      - "docs/**"
      - "examples/**"
      - "CHANGELOG.md"
      - "mkdocs.yml"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force --clean --verbose
