name: Drifting Code Checks
on:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.9"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: make install
      - name: Run checks
        run: |
          make check-all
      - name: Run tests with pytest
        run: |
          make test
      - name: Build and publish the package
        run: |
          make release
